// Mocks generated by Mockito 5.3.2 from annotations
// in todo_app/test/shared/services/http_client/http_client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/app/shared/services/http_client/http_client.dart'
    as _i4;
import 'package:todo_app/app/shared/services/http_client/models/http_client_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientResponse_1 extends _i1.SmartFake
    implements _i3.HttpClientResponse {
  _FakeHttpClientResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.HttpClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  set dio(_i2.Dio? _dio) => super.noSuchMethod(
        Invocation.setter(
          #dio,
          _dio,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<_i3.HttpClientResponse> get(
    String? url, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i5.Future<_i3.HttpClientResponse>.value(_FakeHttpClientResponse_1(
          this,
          Invocation.method(
            #get,
            [url],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i3.HttpClientResponse>);
  @override
  _i5.Future<_i3.HttpClientResponse> delete(
    String? url, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue:
            _i5.Future<_i3.HttpClientResponse>.value(_FakeHttpClientResponse_1(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i3.HttpClientResponse>);
  @override
  _i5.Future<_i3.HttpClientResponse> post(
    String? url, {
    dynamic data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i5.Future<_i3.HttpClientResponse>.value(_FakeHttpClientResponse_1(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.HttpClientResponse>);
  @override
  _i5.Future<_i3.HttpClientResponse> put(
    String? url, {
    dynamic data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i5.Future<_i3.HttpClientResponse>.value(_FakeHttpClientResponse_1(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.HttpClientResponse>);
}
